# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e4c8fceae7bb8ef8395f5fd428eae9c8265170be37391074aa7fefde15dc6567abb28af486b64b1bab634a0003ecd89f4ed4c163096ec15afc160a7f6d3f7c7

test:
  secret_key_base: 28fc5cc45ad36303f05b5313d7152261ee36f9737dfe162ebd332053ea1fbacbf89f03a18b5d25ed1fa8a40b6dd0ad9f83d0acb9b4d07cb517ba3597a8d4f530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
